#!/bin/sh

PROJECT_NAME="MyProject"
PRODUCT_BUNDLE_IDENTIFIER="com.manhpham.myapp.debug"
BUNDLE_SHORT_VERSION_STRING=1.0
BUNDLE_VERSION="1"
SCHEME="MyScheme"
OTHER_SWIFT_FLAGS="-D DEBUG"
PROVISIONING_PROFILE_SPECIFIER="match Development $PRODUCT_BUNDLE_IDENTIFIER"
APPLICATION_TARGET_NAME="MyApp"
SOURCE_DIRECTORY=Sources
SOURCE_TEST_DIRECTORY=SourcesTests
CONFIGURATION=Debug # Debug or Release
UNIT_TEST_DEVICE="iPhone 14 Pro Max"