#!/bin/sh

PROJECT_NAME="MyProject"
PRODUCT_NAME="MyProduct"
PRODUCT_BUNDLE_IDENTIFIER="com.manhpham.myapp.debug"
BUNDLE_SHORT_VERSION_STRING=1.0
DEPLOYMENT_TARGET=12.0
BUNDLE_VERSION="1"
SCHEME="MyScheme"
OTHER_SWIFT_FLAGS="-D DEBUG"
APPLICATION_TARGET_NAME="MyApp"
SOURCE_DIRECTORY=Sources
SOURCE_TEST_DIRECTORY=SourcesTests
UNIT_TEST_DEVICE="iPhone 14 Pro Max"

if [[ $IS_PRODUCTION ]]
then
    PROVISIONING_PROFILE_SPECIFIER="match AppStore $PRODUCT_BUNDLE_IDENTIFIER"
    CONFIGURATION=Release
else
    PROVISIONING_PROFILE_SPECIFIER="match Development $PRODUCT_BUNDLE_IDENTIFIER"
    CONFIGURATION=Debug
fi