default_platform(:ios)

platform :ios do
    before_all do
      setup_circle_ci
    end

    desc "Run unit test"
      lane :unittest do
        run_tests(workspace: ENV['WORKSPACE'],
            devices: [ENV['UNIT_TEST_DEVICE']],
            scheme: ENV['SCHEME'])
      end

    desc "Setup certificate and provisioning profile"
      lane :setup do
        identifider = get_xcconfig_value(
              path: ENV['PATH_XCCONFIG'],
              name: 'PRODUCT_BUNDLE_IDENTIFIER'
            )

        match(app_identifier: identifider, type: "appstore", readonly: true)
      end
      
    desc "Export to testflight"
        lane :export do

            app_store_connect_api_key(
              key_id: ENV['KEY_ID'],
              issuer_id: ENV['ISSUER_ID'],
              key_filepath: ENV['KEY_FILEPATH']
            )

            time = Time.new.strftime("%Y_%d_%m_%H_%M_%S")

            app_name = get_xcconfig_value(
              path: ENV['PATH_XCCONFIG'],
              name: 'PRODUCT_NAME'
            )

            identifider = get_xcconfig_value(
              path: ENV['PATH_XCCONFIG'],
              name: 'PRODUCT_BUNDLE_IDENTIFIER'
            )

            version = get_xcconfig_value(
              path: ENV['PATH_XCCONFIG'],
              name: 'BUNDLE_SHORT_VERSION_STRING'
            )

            build_number_from_test_flight = latest_testflight_build_number(app_identifier: identifider, version: version)
            build_number_from_test_flight += 1

            update_xcconfig_value(
              path: ENV['PATH_XCCONFIG'],
              name: 'BUNDLE_VERSION',
              value: build_number_from_test_flight.to_s
            )

            file = time + "_" + app_name.gsub(' ', '') + "_" + version + "_" + build_number_from_test_flight.to_s + ".ipa"

            update_code_signing_settings(
              use_automatic_signing: false,
              path: ENV['XCODEPROJ'],
              team_id: ENV['FASTLANE_TEAM_ID'],
              code_sign_identity: "iPhone Distribution",
            )

            gym(
                workspace: ENV['WORKSPACE'],
                configuration: ENV['CONFIGURATION'],
                scheme: ENV['SCHEME'],
                export_method: "app-store",
                output_directory: "./fastlane/build",
                output_name: file,
                clean: true,
                export_options: {
                    uploadBitcode: false,
                    uploadSymbols: false,
                    compileBitcode: false,
                    provisioningProfiles: { identifider => ENV['PROVISION_NAME'], "signingStyle": "manual" }
                }
            )

            upload_to_testflight(
              app_identifier: identifider,
              skip_submission: true,
              skip_waiting_for_build_processing: true
            )
    end
end
