platform :ios, '12.0'

target 'MyApp' do
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'PKHUD', '~> 5.0'
  pod 'NSObject+Rx'

  pod 'XCGLogger'
  pod 'SwiftGen', '~> 6.0'
  pod 'Reusable'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'DIKit', :git => 'git@github.com:Liftric/DIKit.git'

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Anchorage'
  pod 'MJRefresh'
  pod 'Then'
  pod 'RxBinding'
  pod 'RxViewController'
  pod 'RxSwiftExt', '~> 5'

end
