platform :ios, '11.0'

target 'VIPPER' do
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'PKHUD', '~> 5.0'

  target 'VIPPERTests' do
    inherit! :search_paths
  end

  target 'VIPPERUITests' do
  end

end
