platform :ios, '12.0'

target 'MyApp' do
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'PKHUD', '~> 5.0'
  pod 'NSObject+Rx'

  pod 'XCGLogger'
  pod 'SwiftGen', '~> 6.0'
  pod 'Reusable'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'Swinject', :git => 'git@github.com:manhpham90vn/Swinject.git', :tag => '2.8.0'
  pod 'SwinjectStoryboard', :git => 'git@github.com:manhpham90vn/SwinjectStoryboard.git', :tag => '2.3.0'

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

end
